apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3scale-rhsso
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-gitops
    name: in-cluster
  project: default
  source:
    path: apps
    repoURL: https://github.com/skadian2309/3scale.git
    targetRevision: HEAD
