apiVersion: v1
kind: LimitRange
metadata:
  name: 3scale-core-resource-limits
  namespace: 3scale
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1536Mi
    defaultRequest:
      cpu: 50m
      memory: 256Mi
    max:
      cpu: "4"
      memory: 32Gi
    type: Container
  - max:
      cpu: "4"
      memory: 32Gi
    type: Pod
