apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3scale
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 3scale
    name: in-cluster
  project: default
  source:
    path: 3scale-rhsso/3scale
    repoURL: https://github.com/skadian2309/3scale.git
    targetRevision: HEAD
