apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhsso
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    namespace: sso
    jsonPointers:
      - /spec/to/kind
  - group: apps.openshift.io
    kind: DeploymentConfig
    name: sso-postgresql
    namespace: sso
    jsonPointers:
      - /spec/template/spec
  - group: apps.openshift.io
    kind: DeploymentConfig
    name: sso
    namespace: sso
    jsonPointers:
      - /spec/template/spec/containers/0/image
      - /status
  destination:
    namespace: sso
    name: in-cluster
  project: default
  source:
    path: 3scale-rhsso/rhsso
    repoURL: https://github.com/skadian2309/3scale.git
    targetRevision: HEAD
