apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhsso
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - group: ""
    kind: Route
    namespace: sso
    jsonPointers:
      - /spec/to/kind  
  destination:
    namespace: sso
    name: in-cluster
  project: default
  source:
    path: 3scale-rhsso/rhsso
    repoURL: https://github.com/skadian2309/3scale.git
    targetRevision: HEAD
